### ISSUE TITLE
Geetest.jsx:120 Uncaught TypeError: ins.onRefresh is not a function

### ISSUE THREAD

**Issue by xgj1988** [xlsdg/react-geetest#1]
报错。出现这个问题
Geetest.jsx:120 Uncaught TypeError: ins.onRefresh is not a function
    at Geetest._load (Geetest.jsx:120)
    at Geetest.jsx:104
    at init (geetest.js:256)
    at geetest.js:276
    at geetest.js:168
    at geetest.js:110

**Comment by xlsdg** [comment]
马上发个版本修复

**Comment by xgj1988** [comment]
@xlsdg 兄dei 速度很快嘛。。发好了说一声撒。

**Comment by xgj1988** [comment]
@xlsdg 兄弟，我看到你现在有些参数没得。是否要加一下。

**Comment by xlsdg** [comment]
马上就好

**Comment by xgj1988** [comment]
@xlsdg 兄弟加个微信嘛 13554783576

**Comment by xlsdg** [comment]
`v2.0.2` 版本试试

**Comment by xgj1988** [comment]
@xlsdg 参数支持最新的吗？

**Comment by xlsdg** [comment]
试一下，我看了文档该加的都加了

**Comment by xgj1988** [comment]
@xlsdg  new_captcha这个参数用的是驼峰还是就这个下划线的方式

**Comment by xlsdg** [comment]
这个参数可以不传，我直接写死了 `new_captcha: true`。

**Comment by xgj1988** [comment]
OK已经可以了的。谢谢哈。

**Comment by xlsdg** [comment]
`v2.2.0` 可以支持传新版的全部参数

**Comment by xgj1988** [comment]
@xlsdg  哥们，又有问题了。。就是这个不支持单机应用，比如我们做的一个混合开发的APP，结果请求的地址是file:////static.geetest.com/static/tools/gt.js 和 file://static.geetest.com/gettype.php

**Comment by xlsdg** [comment]
稍等，马上解决

**Comment by xgj1988** [comment]
@xlsdg  好的谢谢。

**Comment by xlsdg** [comment]
`v2.2.1` 修复了，试一下
