### ISSUE TITLE
初始化后报错

### ISSUE THREAD

**Issue by codeInCat** [xlsdg/react-geetest#3]
初始化传了gt, challenge, onSuccess 进去, 控制台报错了, 说是  ins.onClose is not a function , 是我调用的问题吗 ? 我看你设置了默认值啊

**Comment by xlsdg** [comment]
没初始化成功，或代码调用问题。

**Comment by codeInCat** [comment]
import Geetest from 'react-geetest';

const gtSuccess = (validate) => {
      dispatch({ type: 'gtSuccess', payload: { phone, indexCurrent, funType, validate } });
    };

{ geetest ? <Geetest
          gt={gt}
          challenge={challenge}
          onSuccess={gtSuccess}
        /> : null }


geetest是个boolen  gt和challenge是后台给的   没啥了啊

**Comment by xlsdg** [comment]
没看懂你的代码

**Comment by codeInCat** [comment]
要不你加我下qq说  这个太麻烦了......   419815766

**Comment by codeInCat** [comment]
`{ geetest ? <Geetest
          gt={gt}
          challenge={challenge}
          onSuccess={gtSuccess}
        /> : null }`这是调用组件的  没别的代码了

**Comment by xlsdg** [comment]
先不用 `{ geetest ? : null }` 这个判断试试，直接 `<Geetest gt={gt} challenge={challenge} onSuccess={gtSuccess} />` 显示看看

**Comment by codeInCat** [comment]
还是报那个错 
 Uncaught TypeError: ins.onClose is not a function
    at NECaptcha.eval [as load] (geetest.js?:244)

**Comment by xlsdg** [comment]
换 `import Geetest from 'react-geetest/src/geetest.jsx';` 试试呢？

**Comment by codeInCat** [comment]
各种报错啊.....

**Comment by xlsdg** [comment]
好像是 Geetest 的问题，我这边抽空看一下

**Comment by codeInCat** [comment]
OK

**Comment by xlsdg** [comment]
官方把这个方法去掉了，我一会儿发一个版本。

**Comment by codeInCat** [comment]
好的

**Comment by xlsdg** [comment]
`v3.0.1` 修复了，再试试。

**Comment by codeInCat** [comment]
可以啦   不过还有个问题   就是为什么我拉起极验的时候 是display:none. opacity:0 的;

**Comment by xlsdg** [comment]
那是官方样式吧？
